version: "3.8"

services:
  db:
    image: mongo
    container_name: <project>_db
    volumes:
      - <project>_dbdata:/data/db
    expose:
      - 27017

  # redis:
  #   image: redis:alpine
  #   container_name: <project>_cache
  #   expose:
  #     - 6379

  web:
    build: .
    image: <project>_web
    container_name: <project>_web
    env_file: .env
    environment:
      - MONGO_URI=mongodb://<project>_db:27017/<project>
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=3000
      - VIRTUAL_PATH=/<project>
      - VIRTUAL_PROTO=http
      - WAIT_HOSTS=<project>_db:27017
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - BASE_URL=<project>
    #     - lETSENCRYPT_EMAIL=
    #     - LETSENCRYPT_HOST=
    expose:
      - 3000
    command: sh -c "/entrypoint_nodejs"

volumes:
  <project>_dbdata:

networks:
  default:
    external:
      name: nginx-proxy
