FROM node:12.13.0-alpine AS builder

RUN yarn global add serve
WORKDIR /code

COPY ./src/package.json .
RUN yarn install

COPY ./src .
ADD ./entrypoint_react /entrypoint_react
RUN chmod +x /entrypoint_react
RUN yarn run build